### ISSUE TITLE
Add attribution content when printing projects

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1477]
requirements are in https://github.com/unfoldingWord-dev/ts-requirements/issues/109

**Comment by cckozie** [comment]
Tested on build 131
Entered text on first 3 frames of OBS project and set the chunks to done. Printed including images, not including incomplete chunks. The resulting pdf does not contain any of the chunk text or images.
[en-x-demo1_obs_text_obs.pdf](https://github.com/unfoldingWord-dev/ts-android/files/282201/en-x-demo1_obs_text_obs.pdf)

**Comment by neutrinog** [comment]
this has been fixed.

**Comment by cckozie** [comment]
I'm still seeing this problem on build 137. I'm now seeing the done chunk text, but still no images. (Images were downloaded on my first request to print)

**Comment by PhotoNomad0** [comment]
@neutrinog @cckozie - image printing was not part of this issue.  This issue appears to be complete.  We should open a new issue for image print so we can prioritize it.

**Comment by PhotoNomad0** [comment]
Printing images needs new issue.

**Comment by cckozie** [comment]
Build 141 - Per requirements; the "Attribution of artwork" paragraph needs to be printed when printing OBS.

**Comment by PhotoNomad0** [comment]
@cckozie @neutrinog - I have a new pull request to add image attribution.
