### ISSUE TITLE
Search anomalies on import from door43 dialog

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2062]
If I search only for "num" in translation name I get 3 hits; there is 1 each for 3 users: chuck, joel, and qa99. This is correct based on my searching on git.door43.org

If I add "q" in login name and rerun the search I get the same 3 hits (should just be 1 hit for qa99)
If I change login name to "qa" I don't get any hits  (should be 1 hit for qa99)
If i change login name to "qa9" I get 1 hit (this is correct)
If i change login name to "qa99" I get 1 hit (this is correct)

**Comment by neutrinog** [comment]
fixed.

**Comment by cckozie** [comment]
It's better but still has problems.
Repeated the search as above, but after searching for project "num" and user "qa9" I changed login name to "qa9a" and still get the 1 result. Should not be any results for that search.
Same result if I search with "qy" after the hit with "q".

**Comment by PhotoNomad0** [comment]
Took a look at this at Kos' request.  Found a small logic error that list would not be redrawn immediately if list was empty.

**Comment by PhotoNomad0** [comment]
@neutrinog - I Took a look at this at Kos' request.  Found a small logic error that list would not be redrawn immediately if list was empty.  Pulled in that fix.

**Comment by PhotoNomad0** [comment]
@cckozie - 

I found a problem when too many results were found for repo on Door43.  For example user name “qa5” search “php” will show 5 items.  But if I search for user name “qa5” search “ph” will show 1.  But if I search for user name “qa5” search “” I can see that there are 8 php translations there.

It looks like the wildcard match for repos is finding too many results on Door43, but returns only the first 50, and this drowns out many repos when filtered by user name.
