### ISSUE TITLE
All source texts only appears as Available Online

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2077]
After installing Travis build 1358 on my Lenovo:
![screenshot_2017-04-03-09-15-44](https://cloud.githubusercontent.com/assets/8171759/24613674/9a142064-184e-11e7-900d-4b7b813e60ab.png)

**Comment by cckozie** [comment]
After existing and restarting the app this problem appears to go away.

**Comment by cckozie** [comment]
I had a different experience on a different device. On my Nexus I didn't see the sources as only available for download, but some projects that previously had sources defined now did not, and some showed the Choose source translation(s) screen, but when I went into it there was a source text already selected.
![screenshot_2017-04-03-09-40-48](https://cloud.githubusercontent.com/assets/8171759/24614957/7c379bf8-1852-11e7-9cf0-12fb985562f6.png)

![screenshot_2017-04-03-09-40-56](https://cloud.githubusercontent.com/assets/8171759/24614969/85180f82-1852-11e7-8017-e7451229a4fa.png)

**Comment by PhotoNomad0** [comment]
@cckozie - what book do we heave here?

**Comment by PhotoNomad0** [comment]
Not seeing this on a clean install and a new matthew translation.

**Comment by cckozie** [comment]
Both situations were with previously created Philippians projects. I had uninstalled the previous version of tS, but did not delete the tS folders.

**Comment by cckozie** [comment]
See log file for Lenovo device (first comment) in issue #2080 and log file for Nexus device in issue #2079.

**Comment by PhotoNomad0** [comment]
@neutrinog - issue #2080 seems to be due to missing library.

**Comment by PhotoNomad0** [comment]
@cckozie - cannot reproduce issue #2079 using an old phillipians project on my device.  Suspecting a corrupted migration from a previous upgrade.  Can you send me the folder?

**Comment by cckozie** [comment]
This is the project from my Nexus device.
[en_php_text_reg.zip](https://github.com/unfoldingWord-dev/ts-android/files/890650/en_php_text_reg.zip)

**Comment by PhotoNomad0** [comment]
@cckozie - on  issue #2079, started with an empty translationStudio folder, added the files here under translations, but don't see the error you are seeing.

**Comment by cckozie** [comment]
Interesting. I added the project to my Lenovo's translations folder and it opens fine there too. I noticed, though, that it has two source languages on my Lenovo, both the English and Bengali ULBs. When I try to open it on the Nexus, it shows Bengali as selected, but now I see the English ULB is listed at the bottom under the Available Online languages. Could the install maybe have removed or corrupted existing resource containers or the index db?

**Comment by cckozie** [comment]
Looking in the resource_containers folder on the Nexus I see some issues.
1. There is no en_php_ulb.tsrc file. Only the tn, tq, and udb tsrc files are there.
2. The only en_php_xxx folder on the device is en_php_tn
All 4 entries, ulb, udb, tn, and tq are in the database for resources related to en php projects

**Comment by neutrinog** [comment]
@cckozie this may also be related to the threading issues I fixed. Please review this issue.

**Comment by neutrinog** [comment]
duplicate of #2094

**Comment by cckozie** [comment]
This is still a problem with Travis build 1379. At this point I have only seen it on my phone, but need to test on other devices. On my phone it is very repeatable using the following steps:

Delete the translationStudio folder
Install and open the app.
a) Sometimes the app fully starts and takes me to the login screen.
b) Sometime it hangs with the Performing Updates screen up
c) In both cases, when I look in the resource_containers folder there are somewhere between 100 and 700 files. (Should be about 1000)
If I force stop tS, delete the resource_containers folder, and restart the app, it will recreate the resource_containers folder and load all of the source texts to it. (I do need to force stop the app in order for it to work. If I just end it by exiting/Yes, it will not fully load the resource_containers folder)

**Comment by neutrinog** [comment]
@cckozie I have not been able to reproduce this exact issue however I was able to make a LOT of performance improvements.

* First time loading when creating a new project is faster.
* Resource cards are now only rendered when they are open.
* Closing the resource cards will immediately stop all rendering tasks and just render the source.
* The source renders way faster when scrolling while the resources are closed.

A big issue with things taking a long time is the words resource container takes awhile to unpack on slow devices. This clogs the render queue and makes everything slow. Now, since the resources are closed by default they source should render almost instantly.

**Comment by cckozie** [comment]
So at this point I was only seeing this problem on my phone. More details describing how I ended up with missing resource containers in issue #2090.
Seemingly the issue on my phone was bad behavior caused by apparent interactions between tS and ES File Explorer. Whenever I installed tS from a download from one of the sites or directly from my Google Drive, ES File Explorer was used to open/install it. The installation would either hang or else it would complete with missing RCs in their folder. Then if I closed by any means, including force close, both ES File Explorer and tS, my phone would heat up due to significant battery drain. Even though in Settings it showed that both apps were force closed and not running, when I installed an OS Monitor app I saw that they both were running and together consuming about 95% of the processor. The only way to stop them was to power down the phone.
I then uninstalled ES File Explorer and replaced it with Zenui's File Manager. In this configuration I am able to successfully install tS with all of the RCs showing up in the resource_containers folder. I've tested both as an upgrade from v9 and as a clean install.

Closing this issue, finally!
