### ISSUE TITLE
Pull list of translationWords from Notes Pages

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-android#374]
When I compare the list of important terms on the web to the app there is a disconnect.
See the attached pics.  (I understand that the highlighted KTs in the source text are created by a script.  So this is about the actual list.)  Where does this list come from?
Please note it is our practice that if we have chosen something as a KT/IT we do not write a note. The list includes the base word (verb tense or singular noun) where the server "scrub" does not catch the change in tense, possession or plural.
![luke 1 1](https://cloud.githubusercontent.com/assets/9850185/6486575/e68f36c4-c259-11e4-83c8-f2b62c707118.png)
![app luke 1 1](https://cloud.githubusercontent.com/assets/9850185/6486577/e87af9d2-c259-11e4-8c41-94de21d8c688.png)

 Without the list of KT/IT from the webpage the translator will not see any information about the word.
Thank you for listing the KTs/ITs instead of using commas.

**Comment by neutrinog** [comment]
Good find!
I think we can say this is fixed now :)

![screenshot_030415_110630_am](https://cloud.githubusercontent.com/assets/166412/6490924/90ffb1fc-c25e-11e4-8813-02e436ad4c6e.jpg)

**Comment by ChrisJarka** [comment]
Well, it's better. But it still isn't the list of Important terms from the door43 page.
Case in point - the word 'people' in the ULB does not need to mean 'people group, nation, a people.'

**Comment by ChrisJarka** [comment]
You might want to reopen this. ☺ Sorry.

Blessings,
Christine
407-852-5343

**Comment by neutrinog** [comment]
Here's a snippet from the kt api.

```
{
    "aliases": [
      "nations",
      "people",
      "nation"
    ],
    "cf": [
      
    ],
    "def": "A people group is a group of people who have a common ancestry, culture, or language.<ul><li>People groups usually live together in a particular land or country.</li><li>A people group may be made up of a single tribe, or of many tribes.</li><li>\"People group\" can sometimes be translated as, \"nation,\" but these two terms do not always mean the same thing.</li></ul>",
    "def_title": "Definition",
    "sub": "",
    "term": "people group, nation, a people"
  }
```

You can see in the aliases we have **people** which is caught by the rendering engine to display the term. I know this is not on the door43, but as per the api the app is functioning properly. 

What do you think @jag3773 ? The only way to reliably mark key terms as shown on doo43 100% of the time would be to manually tag each key term occurrence in the text. Otherwise we could get closer to 100% by creating a set of key terms for each frame (not realistic in my opinion). We could slowly move towards the direction of individually tagging key terms in the translation since I know we plan to add that feature to tS in the future. This would have to be a slow fade out thought since none of the source has tagged kt at the moment.

**Comment by neutrinog** [comment]
This is related to https://github.com/Door43/translationStudio2/issues/55

**Comment by ChrisJarka** [comment]
I don't think this is the same issue as #55. 55 seems to be about linking KTs for translators. This issue is for the choice of the words that is displayed in the resources tab and hyperlinked from the source text.
The list of KT in the resources has been manually selected for importance in that particular chunk of text.

**Comment by neutrinog** [comment]
@ChrisJarka that was just for @jag3773 to reference regarding the possible changes needed in order to support better key term detection.

**Comment by jag3773** [comment]
@neutrinog What we could do is add an 'it' entry into the notes json that lists the Import Terms from the notes page in door43 (e.g. https://door43.org/en/bible/notes/luk/01/01).  Then the app could constrain itself to only highlight the terms that are in that list.

Does that sound like a good approach?

**Comment by neutrinog** [comment]
That sounds like a good idea. Not fool proof, but a good idea.
If you want to just throw in the "it" id (e.g. the english word) then I can pull the details from the terms catalog.

**Comment by jag3773** [comment]
Export list of KT for each frame from Door43 into the JSON source for the USX.  Should be sister to "text" and "id" for each frame.

**Comment by neutrinog** [comment]
Current plan is to create a sister element `tw` in the notes catalog.
For example:
```
[
  {
    id:"01-01",
    tn:[]
    tw:[]
  },
  ...
]
```

**Comment by jag3773** [comment]
Updated tW format is at https://api.unfoldingword.org/demo/ts/txt/2/obs/en/kt-en.json.

**Comment by jag3773** [comment]
API side of this is implemented in https://api.unfoldingword.org/obs/txt/1/en/tw_cat-en.json.  Over to you now @neutrinog
